
author = "Davi J. Marcon"
seo_author = "Davi J. Mxrcon"
description = "Biotechnology student and bioinformatician."
seo_description = "Davi Marcon is a Biotechnology graduation student at UFPA ( Federal University of Pará - Brasil)"
tagline = ""
email = "davijosuemarcon@gmail.com"
avatar = "/images/48180517.jpeg"
github = "mxrcon"
url = "mxcon.me"
keywords = "genomics, bioinformatics, bacteria, bactopia, staphopia, nextflow"
rss = false
lastmod = true
favicon = "/images/github.png"
location = "Ananindeua, PA, Brasil"
date_format = "January 2006"
organization = "UFPA - Universidade Federal do Pará"
organization_street = "R. Augusto Corrêa, 01 - Guamá"
organization_city = "Belém"
organization_state = "PA"
organization_zip = " 66075-110"
group = "CGBS & ENGBIO"

# Social Links
[[social]]
    site = "GitHub"
    image = "images/github.png"
    link = "https://github.com/mxrcon"
    user = "mxrcon"

[[social]]
    site = "Twitter"
    image = "images/twitter.png"
    link = "https://twitter.com/"
    user = ""

[[social]]
    site = "LinkedIn"
    image = "images/linkedin.png"
    link = "https://www.linkedin.com/in/"
    user = ""


[[social]]
    site = "ORCID"
    image = "images/orcid.png"
    link = "https://orcid.org/0000-0002-1350-9426"
    user = "0000-0002-1350-9426"

[[social]]
    site = "Google Scholar"
    image = "images/google-scholar.png"
    link = "https://scholar.google.com/citations?user=sBSRYTkAAAAJ"
    user = "sBSRYTkAAAAJ"

# Navigation Sections

[[sections]]
    name = "Publications"
    url = "/publication/"
    weight = 20
    octicon = "journal"

[[sections]]
    name = "Software"
    url = "/software/"
    weight = 5
    octicon = "code"

[[sections]]
    name = "Volunteer"
    url = "/volunteer/"
    weight = 5
    octicon = "rocket"

[[sections]]
    name = "About"
    url = "/about/"
    weight = 5
    octicon = "telescope"
