
author = "Robert A. Petit III, PhD"
seo_author = "Robert A. Petit III, PhD"
description = "Bioinformatician studying bacterial genomics and developer of [Bactopia](https://bactopia.github.io/) and [Staphopia](https://staphopia.emory.edu/) workflows."
seo_description = "Dr. Robert A. Petit III is a bioinformatician at Wyoming Public Health Laboratory and developer of the Bactopia and Staphopia workflows"
tagline = "Dr. Robert A. Petit III is a bioinformatician at Wyoming Public Health Laboratory and developer of the Bactopia and Staphopia workflows"
email = "robbie.petit@gmail.com"
avatar = "/images/profile.png"
github = "rpetit3"
url = "https://www.robertpetit.com"
keywords = "blog, genomics, bioinformatics, bacteria, bactopia, staphopia, nextflow"
rss = true
lastmod = true
favicon = "/images/github.png"
location = "Cheyenne, WY"
date_format = "January 2006"
organization = "Wyoming Public Health Laboratory"
organization_street = "208 South College Drive"
organization_city = "Cheyenne"
organization_state = "WY"
organization_zip = "82002"
group = "Microbiology Laboratories"

# Social Links
[[social]]
    site = "GitHub"
    image = "images/github.png"
    link = "https://github.com/rpetit3"
    user = "rpetit3"

[[social]]
    site = "Twitter"
    image = "images/twitter.png"
    link = "https://twitter.com/rpetit3"
    user = "rpetit3"

[[social]]
    site = "LinkedIn"
    image = "images/linkedin.png"
    link = "https://www.linkedin.com/in/rpetit3"
    user = "rpetit3"

[[social]]
    site = "Impactstory"
    image = "images/impactstory.png"
    link = "https://profiles.impactstory.org/u/0000-0002-1350-9426"
    user = "0000-0002-1350-9426"

[[social]]
    site = "ORCID"
    image = "images/orcid.png"
    link = "https://orcid.org/0000-0002-1350-9426"
    user = "0000-0002-1350-9426"

[[social]]
    site = "Google Scholar"
    image = "images/google-scholar.png"
    link = "https://scholar.google.com/citations?user=sBSRYTkAAAAJ"
    user = "sBSRYTkAAAAJ"

# Navigation Sections
[[sections]]
    name = "Posts"
    url = "/post/"
    weight = 10
    octicon = "project"

[[sections]]
    name = "Publications"
    url = "/publication/"
    weight = 20
    octicon = "journal"

[[sections]]
    name = "Software"
    url = "/software/"
    weight = 5
    octicon = "code"

[[sections]]
    name = "Volunteer"
    url = "/volunteer/"
    weight = 5
    octicon = "rocket"

[[sections]]
    name = "About"
    url = "/about/"
    weight = 5
    octicon = "telescope"
