# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

baseURL = "https://mxrcon.github.io/"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Davi J. Marcon"
theme = "github-style"
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClasses = true
copyright = "&copy; Dr. Robert A. Petit III, 2020-{year}"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[blackfriday]
  nofollowLinks = true
  noreferrerLinks = true
  plainIDAnchors = true
  hrefTargetBlank = true
  extensions = [
    "laxHtmlBlocks", # laxer block handling... let's see what this does?
    "hardLineBreak", # newlines result in line breaks
  ]

[markup.goldmark.renderer]
  unsafe= true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/post/:year/:month/:title/"
