# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

baseURL = "https://www.robertpetit.com/"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "RP3's Site"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true
copyright = "&copy; Robert A. Petit III, 2020-{year}"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[blackfriday]
  nofollowLinks = true
  noreferrerLinks = true
  plainIDAnchors = true
  hrefTargetBlank = true
  extensions = [
    "laxHtmlBlocks", # laxer block handling... let's see what this does?
    "hardLineBreak", # newlines result in line breaks
  ]

[taxonomies]
  tag = "tags"
